#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: alexander
 * Date: 07.03.18
 * Time: 22:17
 */
require_once __DIR__ . '/vendor/autoload.php';

$sorters = [
    new \Alex\Sort\ShellSort,
    new \Alex\Sort\InsertionMergeSort,
    new \Alex\Sort\MergeSort,
    new \Alex\Sort\InPlaceMergeSort,
    new \Alex\Sort\BottomUpMergeSort,
    new \Alex\Sort\QuickSort,
    //new \Alex\Sort\InsertionSort,
    //new \Alex\Sort\SelectSort,
    //new \Alex\Sort\BubbleSort,
];
$dataProvider = new \Alex\Sort\DataProvider;

foreach ($sorters as $sorter) {
    echo get_class($sorter) . "\n";
    foreach (['10', '100', '1000', '10000', '100000'] as $value) {
        $data = $dataProvider('random' . $value);

        $start = microtime(true);
        $result = $sorter($data);
        $duration = microtime(true) - $start;

        echo "Data-Pool: $value  ";
        echo "Dauer: $duration  ";
    }

    echo "\n";
}

